drop table Movie,Person,Genre,Language,Country,Location,M_Producer,M_Director,M_Cast,M_Genre,M_Language,M_Country,M_Location;

create table Movie(
  MID CHAR(9),
  title VARCHAR(50),
  year SMALLINT,
  rating FLOAT(3,1),
  num_votes MEDIUMINT,
  PRIMARY KEY(MID)
);

create table Person (
   PID CHAR(9),
   Name VARCHAR(50),
   DOB DATE,
   Gender ENUM('M','F'),
   PRIMARY KEY(PID)
);

create table Genre (
   GID MEDIUMINT AUTO_INCREMENT,
   Name VARCHAR(11) UNIQUE,
   PRIMARY KEY(GID)
);

create table Language (
   LAID CHAR(3),
   Name VARCHAR(25) UNIQUE,
   PRIMARY KEY(LAID)
);

create table Country (
   CID CHAR(4),
   Name VARCHAR(45) UNIQUE,
   PRIMARY KEY(CID)
);

create table Location (
  LID MEDIUMINT AUTO_INCREMENT,
  Name VARCHAR(100) UNIQUE,
  PRIMARY KEY(LID)
);

create table M_Producer (
  ID MEDIUMINT AUTO_INCREMENT,
  MID CHAR(9),
  PID CHAR(9),
  PRIMARY KEY(ID),
  FOREIGN KEY(MID) REFERENCES Movie(MID),
  FOREIGN KEY(PID) REFERENCES Person(PID)
);

create table M_Director (
  ID MEDIUMINT AUTO_INCREMENT,
  MID CHAR(9),
  PID CHAR(9),
  PRIMARY KEY(ID),
  FOREIGN KEY(MID) REFERENCES Movie(MID),
  FOREIGN KEY(PID) REFERENCES Person(PID)
);

create table M_Cast (
  ID MEDIUMINT AUTO_INCREMENT,
  MID CHAR(9),
  PID CHAR(9),
  PRIMARY KEY(ID),
  FOREIGN KEY(MID) REFERENCES Movie(MID),
  FOREIGN KEY(PID) REFERENCES Person(PID)
);

create table M_Genre (
  ID MEDIUMINT AUTO_INCREMENT,
  MID CHAR(9),
  GID MEDIUMINT,
  PRIMARY KEY(ID),
  FOREIGN KEY(MID) REFERENCES Movie(MID),
  FOREIGN KEY(GID) REFERENCES Genre(GID)
);

create table M_Language (
  ID MEDIUMINT AUTO_INCREMENT,
  MID CHAR(9),
  LAID CHAR(3),
  PRIMARY KEY(ID),
  FOREIGN KEY(MID) REFERENCES Movie(MID),
  FOREIGN KEY(LAID) REFERENCES Language(LAID)
);

create table M_Country (
  ID MEDIUMINT AUTO_INCREMENT,
  MID CHAR(9),
  CID CHAR(4),
  PRIMARY KEY(ID),
  FOREIGN KEY(MID) REFERENCES Movie(MID),
  FOREIGN KEY(CID) REFERENCES Country(CID)
);

create table M_Location (
  ID MEDIUMINT AUTO_INCREMENT,
  MID CHAR(9),
  LID MEDIUMINT,
  PRIMARY KEY(ID),
  FOREIGN KEY(MID) REFERENCES Movie(MID),
  FOREIGN KEY(LID) REFERENCES Location(LID)
);
