create table 12CS10032_Movie (
  MID CHAR(9),
  title VARCHAR(50),
  year SMALLINT,
  rating FLOAT(3,1),
  num_votes MEDIUMINT,
  PRIMARY KEY(MID)
);

create table 12CS10032_Person (
   PID CHAR(9),
   Name VARCHAR(50),
   DOB DATE,
   Gender ENUM('M','F'),
   PRIMARY KEY(PID)
);

create table 12CS10032_Genre (
   GID MEDIUMINT AUTO_INCREMENT,
   Name VARCHAR(11) UNIQUE,
   PRIMARY KEY(GID)
);

create table 12CS10032_Language (
   LAID VARCHAR(3),
   Name VARCHAR(25) UNIQUE,
   PRIMARY KEY(LAID)
);

create table 12CS10032_Country (
   CID VARCHAR(4),
   Name VARCHAR(45) UNIQUE,
   PRIMARY KEY(CID)
);

create table 12CS10032_Location (
  LID MEDIUMINT AUTO_INCREMENT,
  Name VARCHAR(100) UNIQUE,
  PRIMARY KEY(LID)
);

create table 12CS10032_M_Producer (
  ID MEDIUMINT AUTO_INCREMENT,
  MID CHAR(9),
  PID CHAR(9),
  PRIMARY KEY(ID),
  FOREIGN KEY(MID) REFERENCES 12CS10032_Movie(MID),
  FOREIGN KEY(PID) REFERENCES 12CS10032_Person(PID)
);

create table 12CS10032_M_Director (
  ID MEDIUMINT AUTO_INCREMENT,
  MID CHAR(9),
  PID CHAR(9),
  PRIMARY KEY(ID),
  FOREIGN KEY(MID) REFERENCES 12CS10032_Movie(MID),
  FOREIGN KEY(PID) REFERENCES 12CS10032_Person(PID)
);

create table 12CS10032_M_Cast (
  ID MEDIUMINT AUTO_INCREMENT,
  MID CHAR(9),
  PID CHAR(9),
  PRIMARY KEY(ID),
  FOREIGN KEY(MID) REFERENCES 12CS10032_Movie(MID),
  FOREIGN KEY(PID) REFERENCES 12CS10032_Person(PID)
);

create table 12CS10032_M_Genre (
  ID MEDIUMINT AUTO_INCREMENT,
  MID CHAR(9),
  GID MEDIUMINT,
  PRIMARY KEY(ID),
  FOREIGN KEY(MID) REFERENCES 12CS10032_Movie(MID),
  FOREIGN KEY(GID) REFERENCES 12CS10032_Genre(GID)
);

create table 12CS10032_M_Language (
  ID MEDIUMINT AUTO_INCREMENT,
  MID CHAR(9),
  LAID VARCHAR(3),
  PRIMARY KEY(ID),
  FOREIGN KEY(MID) REFERENCES 12CS10032_Movie(MID),
  FOREIGN KEY(LAID) REFERENCES 12CS10032_Language(LAID)
);

create table 12CS10032_M_Country (
  ID MEDIUMINT AUTO_INCREMENT,
  MID CHAR(9),
  CID VARCHAR(4),
  PRIMARY KEY(ID),
  FOREIGN KEY(MID) REFERENCES 12CS10032_Movie(MID),
  FOREIGN KEY(CID) REFERENCES 12CS10032_Country(CID)
);

create table 12CS10032_M_Location (
  ID MEDIUMINT AUTO_INCREMENT,
  MID CHAR(9),
  LID MEDIUMINT,
  PRIMARY KEY(ID),
  FOREIGN KEY(MID) REFERENCES 12CS10032_Movie(MID),
  FOREIGN KEY(LID) REFERENCES 12CS10032_Location(LID)
);
